name: Ubuntu 22.04 CI (GCC 11)

on:
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Makefile
        run: |
          make &&
          ./unit 
